# Generated by Django 4.2.15 on 2024-08-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='checkin_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='checkout_time',
            field=models.IntegerField(),
        ),
    ]
